BloggerBlogBundle_homepage:
    pattern: /
    defaults: { _controller: BloggerBlogBundle:Page:home }
    requirements:
        _method:  GET
BloggerBlogBundle_about:
    pattern: /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET
BloggerBlogBundle_blog_show:
    pattern:  /blog/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
BloggerBlogBundle_comment_create :
    pattern: /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method: POST
        blog_id: \d+
BloggerBlogBundle_blog_create :
    pattern: /blog/create/
    defaults: { _controller: BloggerBlogBundle:Blog:create }
    requirements:
        _method: POST